### PR TITLE
Feat/modify user

### PR DESCRIPTION
**Pull request by GnesisVSS**

### CODE REVIEW

**Comment by spancavil** [comment]
Hi Gene!
For some reason when I login as admin and try to edit some OTHER user information it always appear the information of the admin logged:
image

Also has some conflicts with main branch.

I await these corrections.

**Comment by GnesisVSS** [comment]
Hello Sebas! I fixed the backend and some issues in my branch, now I think it's ok!

**Comment by spancavil** [comment]
Hi Gene!
For some reason it is not saving the country or date of birth. I also see a blinking behavior, it blinks several times when saving it.
image

**Comment by spancavil** [comment]
Now works fine!

**Review by spancavil — APPROVED** [review]

**Pull request merged**
