### PR TITLE
refactor: added wireframe

### PR DESCRIPTION
**Pull request by Bree2003**
added link figma and screenshot of wireframe

### CODE REVIEW

**Review by spancavil — COMMENTED** [review]
Hi girls!
The image link is broken, probably you must upload the image first to some site.
The figma is very good. Only one comment: in the wireframe what's the difference between "dashboard user desktop" and "perfil desktop" ? I think the first one is not necessary.

**Comment by Bree2003** [comment]
Thanks! I have uploaded the images and about the other, one is the view for create an user by an admin and the other is the user's perfil that was logged. In the second view they can change their information.

**Comment by spancavil** [comment]
Ok the images are right now.
Sorry i don't get the meaning of the screen "dashboard user desktop" .. you mention is for create an user, but there is already a screen for that: "crear usuario desktop". Am I right?

**Comment by Bree2003** [comment]
I think I understand now. With my team with discuss about it and decided to eliminate the wireframe dashboard user desktop and make it the profile user view as the principal.

**Comment by spancavil** [comment]
Ok, good. Finally it would be nice to have a screen to change the user password, apart from this main view. (with 3 inputs: password, new password and repeat new password).

**Comment by Bree2003** [comment]
Ok! We will change it

**Review by spancavil — APPROVED** [review]

**Pull request merged**
