### PR TITLE
feat: Password Update user dashboard

### PR DESCRIPTION
**Pull request by loonita**
This component allows users to change their password within a modal dialog. It includes fields for the current password, new password, and confirmation of the new password, with validation to ensure the new passwords match and meet security criteria. Upon submission, it calls an API to update the password and provides feedback based on the response. The form also includes a cancel button to close the modal without making changes.

Capturaa

### CODE REVIEW

**Comment by spancavil** [comment]
Hello Loonita!
I'm getting this error while try to change password (404)
image
I await for corrections

**Comment by loonita** [comment]
hello sebas!
did you pull this change i made https://github.com/alkemyTech/CENCO-MIT-Back-T1/pull/38 ?

**Comment by spancavil** [comment]
Yes, with the necessary backend PR it works. Just remove the alert that looks ugly and think of a message in the same modal or something else that is not an alert haha.
I await for comments.

**Comment by loonita** [comment]
done!

**Review by spancavil — APPROVED** [review]

**Pull request merged**
