### PR TITLE
feat/admin create users

### PR DESCRIPTION
**Pull request by loonita**
This PR implements the user registration functionality into the administration dashboard.

All validations have been implemented as per the requirements presented.

### CODE REVIEW

**Comment by spancavil** [comment]
Hi Loonita! I have 3 observations:

1. Do you validate the age previously to send?
2. Update the user list automatically after a success request.
3. Please check the modal responsiveness.

**Comment by loonita** [comment]
Hi sebas! 😸 

> Hi Loonita! I have 3 observations:
> 
> 1. Do you validate the age previously to send?
> 2. Update the user list automatically after a success request.
> 3. Please check the modal responsiveness.

I have implemented all the request changes in my last commit. Check it out: https://github.com/alkemyTech/CENCO-MIT-Front-T1/pull/10/commits/306597906c4461dff38e11f611559ae11d084282

**Comment by spancavil** [comment]
Very nice!
Only a small bug, when i don't change the default birthday it still sends the request. Please check this and the PR would be approved.

**Comment by loonita** [comment]
This change is contingent on:  https://github.com/alkemyTech/CENCO-MIT-Back-T1/pull/33

**Comment by spancavil** [comment]
Nice!
Done.

**Review by spancavil — APPROVED** [review]

**Pull request merged**
