### PR TITLE
Feat/login

### PR DESCRIPTION
**Pull request by GnesisVSS**
Created the login interface and connected the backend endpoints through the API to validate users. This includes:
- Implementing the login form.
- Integrating API calls for user authentication.
- Ensuring proper handling of user validation responses.

### CODE REVIEW

**Comment by spancavil** [comment]
Hello Gene!
The design is excellent! I couldn't try it because the .env variables is missing. Please add all of them to the readme.
Looking forward.

**Comment by spancavil** [comment]
Also the structure of folders and files and redux organization is good.

**Comment by GnesisVSS** [comment]
Hello Sebas! The .env variables are in the backend project. We need to run both the backend and the frontend simultaneously to test the login functionality.

**Comment by spancavil** [comment]
Hi Gene! Yes, I mean that the variables for the front should also be in the front readme. For example, I have the following:
Screenshot from 2024-08-16 12-07-48

I await for your comments.

**Comment by kamivillabla** [comment]
> Hi Gene! Yes, I mean that the variables for the front should also be in the front readme. For example, I have the following: Screenshot from 2024-08-16 12-07-48
> 
> I await for your comments.

This is the variable VITE_BACKEND_URL=http://localhost:3000

**Comment by spancavil** [comment]
Yes Kamila, but I mean it should be in the readme too. Please add it and all the variables that are going to be used.

**Comment by GnesisVSS** [comment]
Implemented requested changes

**Comment by spancavil** [comment]
Excellent!

**Review by spancavil — APPROVED** [review]

**Pull request merged**
